# Project-wide Gradle settings.

# تفعيل بيئة AndroidX الحديثة
android.useAndroidX=true

# تفعيل الـ Jetifier لتحويل المكتبات القديمة تلقائياً وتجاوز خطأ البناء
android.enableJetifier=true

# إعدادات الأداء والذاكرة لـ Gradle أثناء البناء على السيرفر
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.defaults.buildfeatures.buildconfig=true
